sonar.sourceEncoding = UTF-8
sonar.sources = .
sonar.exclusions = node_modules/**,coverage/**,.svelte-kit/**,build/**
sonar.test.inclusions = **/*.test.ts,**/*.spec.ts
sonar.javascript.lcov.reportPaths = coverage/lcov.info
sonar.typescript.tsconfigPaths = tsconfig.json
