name: Docker CI workflow 

on:
  push:
    branches: ["main"]
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches: ["main"]
    types:
      - opened
      - reopened
      - synchronize
jobs:

  docker-build:
    runs-on: ubuntu-latest
    name: Run docker build  
    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: planthor/planthorwebapp

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Define docker image name
        id: define_docker_image
        run: |
          echo "DOCKER_BUILD_CHECKS_ANNOTATIONS=true" >> $GITHUB_ENV
          echo "DOCKER_BUILD_RECORD_UPLOAD=false" >> $GITHUB_ENV
          echo "DOCKER_BUILD_SUMMARY=true" >> $GITHUB_ENV
          DOCKER_TAG=""
          PUSH_ENABLED=false
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            DOCKER_TAG="latest"
            echo DOCKER_IMAGE="ghcr.io/planthor/planthorwebapp:$DOCKER_TAG" >> "$GITHUB_OUTPUT"
            PUSH_ENABLED=true
          elif [[ $GITHUB_REF =~ ^refs/tags/* ]]; then
            DOCKER_TAG="${{  github.ref_name }}"
            echo DOCKER_IMAGE="ghcr.io/planthor/planthorwebapp:$DOCKER_TAG" >> "$GITHUB_OUTPUT"
            PUSH_ENABLED=true
          else
            DOCKER_TAG="${{ github.head_ref }}"
            DOCKER_TAG=${DOCKER_TAG//\//-}
            echo DOCKER_IMAGE="planthordev/planthorwebapp:$DOCKER_TAG" >> "$GITHUB_OUTPUT"
          fi
          echo PUSH_ENABLED=$PUSH_ENABLED >> "$GITHUB_OUTPUT"

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:      
          file: ./Dockerfile
          tags: ${{ steps.define_docker_image.outputs.DOCKER_IMAGE }}
          github-token: ${{ github.token }}
          push: ${{ steps.define_docker_image.outputs.PUSH_ENABLED }}
          cache-from: type=gha
          cache-to: type=gha,mode=min
