name: Docker CI workflow 

on:
  push:
    branches: ["main"]
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches: ["main"]
    types:
      - opened
      - reopened
      - synchronize
jobs:

  docker-build:
    runs-on: ubuntu-latest
    name: Run docker build  
    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: planthor/planthorwebapp

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker config environment
        run: |
          echo "DOCKER_BUILD_CHECKS_ANNOTATIONS=true" >> $GITHUB_ENV
          echo "DOCKER_BUILD_RECORD_UPLOAD=false" >> $GITHUB_ENV
          echo "DOCKER_BUILD_SUMMARY=true" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:      
          file: ./Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          github-token: ${{ github.token }}
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha
          cache-to: type=gha,mode=min
