name: Docker CI workflow 

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  docker-build:
    runs-on: ubuntu-latest
    name: Run docker build  
    steps:
      
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Define docker image name
        id: define_docker_image
        run: |
          DOCKER_TAG="testcandidates-$(date +%Y%m%d%H%M%S)"
          echo DOCKER_IMAGE="planthordev/client-frontend:$DOCKER_TAG" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:      
          file: ./Dockerfile
          tags: ${{ steps.define_docker_image.outputs.DOCKER_IMAGE }}
          github-token: ${{ github.token }}
          # only push at main branch
          push: ${{ github.ref == 'refs/heads/main' }}
